export const termsData = [{
    lastUpdated: `October 12th 2023`,
    text: `Please read these Terms of Service (the “<strong>Terms</strong>”) and our <a href="#">Privacy Notice</a> (“<strong>Privacy Notice</strong>”) carefully because they govern your use of the CopyAI, Inc. (“<strong>Copy.AI</strong>”) website located at www.copy.ai (the “<strong>Site</strong>”), Copy.AI’s copy content generation services, and any copy content generated by Copy.AI’s services for you based on your User Content (defined below) (“<strong>Generated Content</strong>”). To make these Terms easier to read, the Site, our services, and the Generated Content are collectively called the “<strong>Services</strong>.”`,
},
{
    heading: ``,
    text: `<strong>IMPORTANT NOTICE REGARDING ARBITRATION FOR U.S. CUSTOMERS: WHEN YOU AGREE TO THESE TERMS YOU ARE AGREEING (WITH LIMITED EXCEPTION) TO RESOLVE ANY DISPUTE BETWEEN YOU AND COPY.AI THROUGH BINDING, INDIVIDUAL ARBITRATION RATHER THAN IN COURT. PLEASE REVIEW CAREFULLY SECTION 16 \"DISPUTE RESOLUTION\" BELOW FOR DETAILS REGARDING ARBITRATION.`,
},
{
    text: ` <strong>1. Agreement to Terms.</strong> By using our Services, you agree to be bound by these Terms. If you do not agree to be bound by these Terms, do not use the Services. If you are accessing and using the Services on behalf of a company (such as your employer) or other legal entity, you represent and warrant that you have the authority to bind that entity to these Terms. In that case, “you” and “your” will refer to that entity.`
},
{
    text: `<strong>2. Privacy Notice. </strong> Please review our Privacy Notice, which also governs your use of the Services, for information on how we collect, use and share your information.`
},
{
    text: `<strong>3. Changes to these Terms or the Services. </strong> We may update the Terms from time to time in our sole discretion. If we do, we’ll let you know by posting the updated Terms on the Site and/or may also send other communications. It’s important that you review the Terms whenever we update them or you use the Services. If you continue to use the Services after we have posted updated Terms it means that you accept and agree to the changes. If you don’t agree to be bound by the changes, you may not use the Services anymore. Because our Services are evolving over time we may change or discontinue all or any part of the Services, at any time and without notice, at our sole discretion.`
},
{
    heading: `<strong>4. Who May Use the Services?</strong>`,
    text: `You may use the Services only if you are 18 years or older and capable of forming a binding contract with Copy.AI, and not otherwise barred from using the Services under applicable law. </br>  For certain features of the Services you will need an account. It is important that you provide us with accurate, complete and current account information and keep this information up to date. If you don’t, we might have to suspend or terminate your account. To protect your account, keep the account details and password confidential, and notify us right away of any unauthorized use. You are responsible for all activities that occur under your account.`
},
{
    text: `<strong>5. Feedback.</strong> We appreciate feedback, comments, ideas, proposals and suggestions for improvements to the Services (“Feedback”). If you choose to submit Feedback, you agree that we are free to use it without any restriction or compensation to you.`
},
{
    text: `<strong>6. Subscriptions.</strong> Copy.AI requires payment of a fee for use of the Services (or certain portions thereof) and you agree to pay such fees.`
},
{
    text: `<strong>(a)</strong>     General. When you purchase a subscription for the Services (“<strong>Subscription</strong>”), you expressly authorize us (or our third-party payment processor) to charge you for such Subscription. We may ask you to supply additional information relevant to your Subscription, including your credit card number, the expiration date of your credit card and your email and postal addresses for billing and notification (such information, “<strong>Payment Information</strong>”). You represent and warrant that you have the legal right to use all payment method(s) represented by any such Payment Information. When you initiate a Subscription, you authorize us to provide your Payment Information to third parties so we can complete the transaction related to your Subscription and to charge your payment method for the type of Subscription you have selected (plus any applicable taxes and other charges). You may need to provide additional information to verify your identity before completing your Subscription (such information is included within the definition of Payment Information). By initiating a Subscription, you agree to the pricing, payment and billing policies applicable to such fees and charges, as posted or otherwise communicated to you. All payments for Subscriptions are non-refundable and non-transferable except as expressly provided in these Terms. All fees and applicable taxes, if any, are payable in United States dollars.`
},
{
    text: `<strong>(b)</strong> Subscriptions. If you purchase a Subscription, you will be charged the annual Subscription fee, plus any applicable taxes, and other charges (“<strong>Subscription Fee)</strong>”), at the beginning of your Subscription and each year thereafter, at the then-current Subscription Fee. BY PURCHASING A SUBSCRIPTION, YOU AUTHORIZE COPY.AI TO INITIATE RECURRING NON-REFUNDABLE PAYMENTS AS SET FORTH BELOW. If you purchase a Subscription, we (or our third-party payment processor) will automatically charge you each year on the anniversary of the commencement of your Subscription, using the Payment Information you have provided until you cancel your Subscription. No less than thirty (30) days and no more than sixty (60) days before your Subscription term ends, or otherwise in accordance with applicable law, Copy.AI will send you a reminder with the then-current Subscription Fee. By agreeing to these Terms and electing to purchase a Subscription, you acknowledge that your Subscription has recurring payment features and you accept responsibility for all recurring payment obligations prior to cancellation of your Subscription by you or Copy.AI. Your Subscription continues until cancelled by you or we terminate your access to or use of the Services or Subscription in accordance with these Terms.`
},
{
    text: `<strong>(c)</strong> Cancelling Your Subscription. You may cancel your Subscription for a full refund within five (5) calendar days of your initial purchase. AFTER THAT, YOUR PURCHASE IS FINAL AND YOU WILL NOT BE ABLE TO CANCEL THE PURCHASE AND/OR RECEIVE A REFUND OF YOUR SUBSCRIPTION FEE AT ANY TIME. But if something unexpected happens in the course of completing a transaction, we reserve the right to cancel your transaction for any reason; if we cancel your transaction we will refund any payment you have already remitted to us for such transaction. Without limiting the foregoing, you may cancel your Subscription at any time, but please note that such cancellation will be effective at the end of the then-current Subscription period. EXCEPT AS SET FORTH ABOVE WITH RESPECT TO YOUR INITIAL SUBSCRIPTION PURCHASE, YOU WILL NOT RECEIVE A REFUND OF ANY PORTION OF THE SUBSCRIPTION FEE PAID FOR THE THEN CURRENT SUBSCRIPTION PERIOD AT THE TIME OF CANCELLATION. To cancel, you can send an email to cancel@copy.ai. You will be responsible for all Subscription Fees (plus any applicable taxes and other charges) incurred for the then-current Subscription period. If you cancel, your right to use the Services will continue until the end of your then current Subscription period and will then terminate without further charges.`
},
{
    text: `<strong>(d)</strong> Free Trials. We may offer to certain qualifying users paid Subscriptions on a free trial basis (“Free Trial”) for a specified period of time. If we offer you a Free Trial, the specific terms of your Free Trial will be provided at signup. Your use of the Free Trial is subject to your compliance with such specific terms. Certain limitations may exist with respect to combining Free Trials with any other offers. Except as may otherwise be provided in the specific terms for the Free Trial offer, Free Trials are only available to users who have not previously held a paid Subscription. When you agree to a Free Trial, you are also agreeing to sign up for a paid Subscription as described above and, consequently, unless you cancel your Subscription prior to the end of your Free Trial, we (or our third party payment processor) will begin charging your payment method on a recurring annual basis for the applicable annual fee (plus any applicable taxes and other charges) at the end of the Free Trial until you cancel your Subscription. If you wish to avoid charges to your Payment Information, you must cancel your Subscription prior to midnight Eastern Time on the last day of your Free Trial period. Instructions for cancelling your subscription are stated in the section above titled “Canceling Your Subscription.”`
},
{
    heading: `<strong>7. Your Content.</strong>`,
    text: `<strong>(a)</strong> Posting Content. Our Services may allow you to store or share content such as text (in posts or communications with others), files, documents, graphics, images, music, software, audio and video. Anything (other than Feedback) that you post or otherwise make available through the Services is referred to as “<strong>User Content.</strong>” Copy.AI does not claim any ownership rights in any User Content and nothing in these Terms will be deemed to restrict any rights that you may have to your User Content.`
},
{
    text: `<strong>(b)</strong> Permissions to Your User Content. By making any User Content available through the Services you hereby grant to Copy.AI, its licensors, and their affiliates a non-exclusive, transferable, perpetual, irrevocable, worldwide, royalty-free, fully paid-up license, with the right to sublicense, to use, host, store, copy, communicate, modify, create derivative works based upon, distribute, publish, publicly display, and publicly perform your User Content in connection with Copy.AI, its licensors, and their affiliate providing, operating, securing, and improving their services.`
},
{
    text: `<strong>(c)</strong> Your Responsibility for User Content. You are solely responsible for all your User Content. You represent and warrant that you have (and will have) all rights that are necessary to grant us the license rights in your User Content under these Terms. You represent and warrant that neither your User Content, nor your use and provision of your User Content to be made available through the Services, nor any use of your User Content by Copy.AI on or through the Services will infringe, misappropriate or violate a third party’s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.`
},
{
    text: `<strong>(d)</strong> Removal of User Content. You can remove your User Content by specifically deleting it. You should know that in certain instances, some of your User Content, (such as posts or comments you make), may not be completely removed and copies of your User Content may continue to exist on the Services. To the maximum extent permitted by law, we are not responsible or liable for the removal or deletion of (or the failure to remove or delete) any of your User Content.`
},
{
    text: `<strong>(e)</strong> Your Use of Generated Content. Subject to your compliance with these Terms, Copy.AI hereby grants you a non-exclusive, worldwide, license, with the right to sublicense, to use, copy, modify, sell, create derivative works based upon, distribute, publicly display, and publicly perform Generated Content for your lawful business purposes.`
},
{
    text: `<strong>(f)</strong>  Ownership of Intellectual Property. We may make available through the Services content that is subject to intellectual property rights, including Generated Content. We and our licensors (as applicable) retain all rights to that content.`
},
{
    heading: `<strong>8. Usage Requirements, General Prohibitions, and Copy.AI’s Enforcement Rights.</strong>`,
    subHeading: `<strong> (a)</strong> You agree that you will use the Services:`,
    points: [
        `Only in a lawful manner and in compliance with all applicable laws;`,
        `In accordance with the Terms, the license granted in Section 7(e), and any documentation, usage guidelines, parameters, and other requirements provided to you by Copy.AI or its licensors, as may be modified by Copy.AI or its licensors from time to time;`,
        `In a manner that does not infringe, misappropriate, or otherwise violate any of Copy.AI’s or its licensors’ rights or those of any other person or entity;`,
        `As it relates to Generated Content, in a manner that is consistent with the OpenAI mission and Charter, which is incorporated herein by reference, as determined by OpenAI in its sole discretion;`,
        `In a manner that does not violate these Terms, any agreement between you and anyone else or our or a third party’s rights; and`,
        `In compliance with, and you will not attempt to circumvent, any call rate limits or other restrictions that may be established by Copy.AI or its licensors from time to time.`,
    ],
    text: `<br/>You further agree that you will make reasonable efforts to reduce the likelihood, severity, and scale of any societal harm caused by your use of the Services (including the use and sharing of Generated Content) by following the OpenAI API Usage Guidelines. Copy.AI and OpenAI may request information from you regarding your efforts to reduce safety risks, and you agree to provide such information.  Such information may be used to assess compliance with these Terms as well as to inform improvements to the Services (including any components thereof).`
},
{
    subHeading: `<strong> (b)</strong> You agree not to do any of the following:`,
    points: [
        `Post, upload, publish, submit or transmit any User Content that: (i) infringes, misappropriates or violates a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any person or entity; or (vii) promotes illegal or harmful activities or substances;`,
        `Distribute, sell, lend, transfer or grant any rights in or to any or all of the Services, (except for Generated Content as permitted under this Agreement);`,
        `Create any software that functions substantially the same as the Services (including any component thereof) and offer it to third parties;`,
        `Modify, alter, tamper with, repair or otherwise create derivative works (except as permitted by Section 7(e)) of the Services, or attempt to do so;`,
        `Use the Services in connection with any spyware, malware, virus, worm, trojan horse, or other malicious or harmful code, or any software application not expressly and knowingly authorized by users prior to being downloaded or installed on their computer or other electronic device;`,
        `Use the Services to discover any underlying components of Copy.AI’s or its licensors’ models, algorithms, and systems, such as exfiltrating the weights of any of Copy.AI’s or its licensors’ models by cloning via logits;`,
        `Remove, obscure, or alter any notice, including any notice of intellectual property right appearing on or contained within the Services (including any component thereof);`,
        `Interfere or attempt to interfere in any manner with the functionality or proper working of the Services (including any component thereof);`,
        `Use, display, mirror or frame the Services or any individual element within the Services, Copy.AI’s name, any Copy.AI trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page, without Copy.AI’s express written consent;`,
        `Access, tamper with, or use non-public areas of the Services, Copy.AI’s computer systems, or the technical delivery systems of Copy.AI’s providers;`,
        `Attempt to probe, scan or test the vulnerability of any Copy.AI system or network or breach any security or authentication measures;`,
        `Avoid, bypass, remove, deactivate, impair, descramble or otherwise circumvent any technological measure implemented by Copy.AI or any of Copy.AI’s providers or any other third party (including another user) to protect the Services;`,
        `Attempt to access or search the Services or download content from the Services using any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than the software and/or search agents provided by Copy.AI;`,
        `Use web scraping, web harvesting, or web data extraction methods to extract data from the Services (including Generated Content), or Copy.AI’s, its licensors’, and their affiliates’ software, models, or systems.`,
        `Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation;`,
        `Use any meta tags or other hidden text or metadata utilizing a Copy.AI trademark, logo URL or product name without Copy.AI’s express written consent;`,
        `Use the Services, or any portion thereof, for any commercial purpose or for the benefit of any third party or in any manner not permitted by these Terms;`,
        `Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services to send altered, deceptive or false source-identifying information;`,
        `Decipher, decompile, disassemble, reverse assemble, reverse compile, decompile, translate, or reverse engineer any component or software used to provide the Services, discover the source code of any component of the Services, or attempt to do any of the foregoing;`,
        `Interfere with, or attempt to interfere with, the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Services;`,
        `Collect or store any personally identifiable information from the Services from other users of the Services without their express permission;`,
        `Impersonate or misrepresent your affiliation with any person or entity;`,
        `Provide or upload any information to the Services that is “Protected Health Information” as defined under the Health Insurance Portability and Accountability Act;`,
        `Use the Services in a way that causes societal harm including, but not limited to, (i) misleading end users that any Generated Content was human-generated for generative use cases that do not involve a human in the loop, (ii) generating spam, and (iii) generating content for dissemination in electoral campaigns;`,
        `Use the Services in a way that violates any applicable law or regulation including, but not limited to, (i) illegal activities such as child pornography, gambling, piracy, violating copyright, trademark or other intellectual property laws, (ii) accessing or authorizing anyone to access the Services from an embargoed country as prohibited by the United States government, and (iii) threating, stalking, defaming, defrauding, degrading, victimizing, or intimidating anyone for any reason; and`,
        `Encourage or enable any other individual to do any of the foregoing.`,
    ],
    text: `<br/>Copy.AI is not obligated to monitor access to or use of the Services or to review or edit any content. However, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms and to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any content, including User Content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider it objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.`
},
{
    text: `<strong>9. DMCA/Copyright Policy. </strong> Copy.AI respects copyright law and expects its users to do the same. It is Copy.AI’s policy to terminate in appropriate circumstances account holders who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders. Please see Copy.AI’s Copyright Policy at copy.ai/copyright-policy, for further information.`
},
{
    text: `<strong>10. Links to Third Party Websites or Resources. </strong> The Services may allow you to access third-party websites or other resources. We provide access only as a convenience and are not responsible for the content, products or services on or available from those resources or links displayed on such websites. You acknowledge sole responsibility for and assume all risk arising from, your use of any third-party resources.`
},
{
    text: `<strong>11. Termination. </strong> We may suspend or terminate your access to and use of the Services, including suspending access to or terminating your account, at our sole discretion, at any time and without notice to you. You may cancel your account at any time by sending us an email at cancel@copy.ai. Upon any termination, discontinuation or cancellation of the Services or your account, the following Sections will survive: 6(a), 6(b), 6(c) (only for payments due and owing to Copy.AI prior to the termination), 6(d), 7(b), 7(c), 7(e), 7(f), 8, 9, 11, 12, 13, 14, 15, 16 and 17.`
},
{
    text: `<strong>12. Warranty Disclaimers. </strong> THE SERVICES ARE PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE AND OUR LICENSORS EXPLICITLY DISCLAIM ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. We and our licensors make no warranty that the Services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. We make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness or reliability of any information or content on the Services.`
}, {
    text: `<strong>13. Indemnity. </strong> You will indemnify and hold Copy.AI, its licensors, their affiliates, and each of their officers, directors, employees, representatives, and agents, harmless from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees arising out of or in any way connected with (a) your access to or use of the Services, (b) your User Content, (c) your violation of these Terms, or (d) your actual or alleged infringement, misappropriation, or violation of Copy.AI’s, its licensors’, or any third party’s intellectual property or proprietary rights.`
}, {
    heading: `<strong> 14. Limitation of Liability. </strong>`,
    text: `<strong>(a)</strong> TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER COPY.AI NOR ITS SERVICE PROVIDERS AND LICENSORS INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOST REVENUES, LOST SAVINGS, LOST BUSINESS OPPORTUNITY, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT COPY.AI OR ITS LICENSORS OR ITS SERVICE PROVIDERS HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.`
}, {

    text: `<strong>(b)</strong> TO THE MAXIMUM EXTENT PERMITTED BY THE LAW OF THE APPLICABLE JURISDICTION, IN NO EVENT WILL COPY.AI’S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES EXCEED THE AMOUNTS YOU HAVE PAID OR ARE PAYABLE BY YOU TO COPY.AI FOR USE OF THE SERVICES OR ONE HUNDRED DOLLARS ($100), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO COPY.AI, AS APPLICABLE.`
}, {

    text: `<strong>(a)</strong> THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN COPY.AI AND YOU.`
}, {
    text: `<strong> 15. Governing Law and Forum Choice. </strong> These Terms and any action related thereto will be governed by the Federal Arbitration Act, federal arbitration law, and the laws of the State of California, without regard to its conflict of laws provisions. Except as otherwise expressly set forth in Section 16 “Dispute Resolution,” the exclusive jurisdiction for all Disputes (defined below) that you and Copy.AI are not required to arbitrate will be the state and federal courts located in Santa Clara County, and you and Copy.AI each waive any objection to jurisdiction and venue in such courts.`
},
{
    heading: `<strong> 16. Dispute Resolution. </strong>`,
    text: `<strong> (a) </strong> Mandatory Arbitration of Disputes. We each agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Services (collectively, “<strong> Disputes</strong>”) will be resolved <strong> solely by binding, individual arbitration and not in a class, representative or consolidated action or proceeding.</strong> You and Copy.AI agree that the U.S. Federal Arbitration Act governs the interpretation and enforcement of these Terms, and that you and Copy.AI are each waiving the right to a trial by jury or to participate in a class action. This arbitration provision shall survive termination of these Terms.`
}, {
    text: `<strong> (b) </strong> Exceptions. As limited exceptions to Section 16(a) above: (i) we both may seek to resolve a Dispute in small claims court if it qualifies; and (ii) we each retain the right to seek injunctive or other equitable relief from a court to prevent (or enjoin) the infringement or misappropriation of our intellectual property rights.`
}, {
    text: `<strong> (c) </strong> Conducting Arbitration and Arbitration Rules. The arbitration will be conducted by the American Arbitration Association (“<strong>AAA</strong>”) under its Consumer Arbitration Rules (the “<strong>AAA Rules</strong>”) then in effect, except as modified by these Terms. The AAA Rules are available at www.adr.org or by calling 1-800-778-7879. A party who wishes to start arbitration must submit a written Demand for Arbitration to AAA and give notice to the other party as specified in the AAA Rules. The AAA provides a form Demand for Arbitration at www.adr.org.`
}, {
    text: `Any arbitration hearings will take place in the county (or parish) where you live, unless we both agree to a different location. The parties agree that the arbitrator shall have exclusive authority to decide all issues relating to the interpretation, applicability, enforceability and scope of this arbitration agreement.`
}, {
    text: `<strong> (d) </strong> Arbitration Costs. Payment of all filing, administration and arbitrator fees will be governed by the AAA Rules, and we won’t seek to recover the administration and arbitrator fees we are responsible for paying, unless the arbitrator finds your Dispute frivolous. If we prevail in arbitration we’ll pay all of our attorneys’ fees and costs and won’t seek to recover them from you. If you prevail in arbitration you will be entitled to an award of attorneys’ fees and expenses to the extent provided under applicable law.`
}, {
    text: `<strong> (e) </strong> Injunctive and Declaratory Relief. Except as provided in Section 16(b) above, the arbitrator shall determine all issues of liability on the merits of any claim asserted by either party and may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual claim. To the extent that you or we prevail on a claim and seek public injunctive relief (that is, injunctive relief that has the primary purpose and effect of prohibiting unlawful acts that threaten future injury to the public), the entitlement to and extent of such relief must be litigated in a civil court of competent jurisdiction and not in arbitration. The parties agree that litigation of any issues of public injunctive relief shall be stayed pending the outcome of the merits of any individual claims in arbitration.`
}, {
    text: `<strong> (f) </strong> Class Action Waiver.<strong> YOU AND COPY.AI AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. </strong> Further, if the parties’ Dispute is resolved through arbitration, the arbitrator may not consolidate another person’s claims with your claims, and may not otherwise preside over any form of a representative or class proceeding. If this specific provision is found to be unenforceable, then the entirety of this Dispute Resolution section shall be null and void. `
}, {
    text: `<strong> (g) </strong> Severability. With the exception of any of the provisions in Section 16(f) of these Terms (“<strong> Class Action Waiver</strong> ”), if an arbitrator or court of competent jurisdiction decides that any part of these Terms is invalid or unenforceable, the other parts of these Terms will still apply.`
}, {
    heading: `<strong> 17. General Terms.</strong>`,
    text: `<strong> (a)</strong> Reservation of Rights. Copy.AI and its licensors exclusively own all right, title and interest in and to the Services, including all associated intellectual property rights. Notwithstanding the foregoing, Copy.AI’s licensor, OpenAI LLC, exclusively owns all right, title and interest in and to Generated Content. Copy.AI claims no ownership of Generated Content. You acknowledge that the Services are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Services.`,
}, {
    text: `<strong> (b) </strong> Entire Agreement. These Terms constitute the entire and exclusive understanding and agreement between Copy.AI and you regarding the Services, and these Terms supersede and replace all prior oral or written understandings or agreements between Copy.AI and you regarding the Services. If any provision of these Terms is held invalid or unenforceable by an arbitrator or a court of competent jurisdiction, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect. You may not assign or transfer these Terms, by operation of law or otherwise, without Copy.AI’s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null. Copy.AI may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.`
}, {
    text: `<strong> (c) </strong> Notices. Any notices or other communications provided by Copy.AI under these Terms will be given: (i) via email; or (ii) by posting to the Services. For notices made by email, the date of receipt will be deemed the date on which such notice is transmitted.`
}, {
    text: `<strong> (d) </strong> Waiver of Rights. Copy.AI’s failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Copy.AI. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.`
}, {
    text: `<strong> 18. Contact Information.  </strong>  If you have any questions about these Terms or the Services, please contact Copy.AI at:`,
    content: `<p class='mb-2'>at:</p><p>CopyAI, Inc.</p><br/><p>Tennessee, Memphis - Colonnade<br>1661 International Dr<br>Memphis, TN 38120, USA</p><br/><p><a href="mailto:legal@copy.ai">legal@copy.ai</a></p><br/><p>571-758-3823</p><br/><p>This website uses cookies. We use cookies to personalise content and ads, to provide social media features and to analyse our traffic. We also share information about your use of our site with our social media, advertising and analytics partners who may combine it with other information that you’ve provided to them or that they’ve collected from your use of their services.</p><br/><p>Cookies are small text files that can be used by websites to make a user's experience more efficient.</p><br/><p>The law states that we can store cookies on your device if they are strictly necessary for the operation of this site. For all other types of cookies we need your permission.</p><br/><p>This site uses different types of cookies. Some cookies are placed by third party services that appear on our pages.</p><br/><p>You can at any time change or withdraw your consent from the Cookie Declaration on our website.</p><br/><p>Learn more about who we are, how you can contact us and how we process personal data in our Privacy Policy.</p><br/><p>Please state your consent ID and date when you contact us regarding your consent.</p><br/><p>Your consent applies to the following domains: www.copy.ai</p><br/><p>Cookie declaration last updated on 8/29/24 by Cookiebot:</p>`

}
]




export const jsonData = [{
    category: "Necessary (30)",
    description: "Necessary cookies help make a website usable by enabling basic functions like page navigation and access to secure areas of the website. The website cannot function properly without these cookies.",
    columns: [
        "Name",
        "Provider",
        "Purpose",
        "Maximum Storage Duration",
        "Type"
    ],
    rows: [
        {
            Name: "__cf_bm [x2]",
            Provider: "verisoul.ai, Vimeo",
            Purpose: "This cookie is used to distinguish between humans and bots. This is beneficial for the website, in order to make valid reports on the use of their website.",
            "Maximum Storage Duration": "1 day",
            Type: "HTTP Cookie"
        },
        {
            Name: "__mp_opt_in_out_#",
            Provider: "scribehow.com",
            Purpose: "Stores the user's cookie consent state for the current domain",
            "Maximum Storage Duration": "Session",
            Type: "HTTP Cookie"
        },
        {
            Name: "__Secure-3PAPISID",
            Provider: "Google",
            Purpose: "Pending",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "__Secure-3PSID",
            Provider: "Google",
            Purpose: "Pending",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "__Secure-3PSIDCC",
            Provider: "Google",
            Purpose: "Pending",
            "Maximum Storage Duration": "1 year",
            Type: "HTTP Cookie"
        },
        {
            Name: "_cfuvid",
            Provider: "Vimeo",
            Purpose: "This cookie is a part of the services provided by Cloudflare - Including load-balancing, deliverance of website content and serving DNS connection for website operators.",
            "Maximum Storage Duration": "Session",
            Type: "HTTP Cookie"
        },
        {
            Name: "_gid",
            Provider: "Google",
            Purpose: "Registers a unique ID that is used to generate statistical data on how the visitor uses the website.",
            "Maximum Storage Duration": "1 day",
            Type: "HTTP Cookie"
        },
        {
            Name: "_gf",
            Provider: "Cookiebot",
            Purpose: "Used to count the number of sessions to the website, necessary for optimizing CMP provider delivery.",
            "Maximum Storage Duration": "Session",
            Type: "Pixel Tracker"
        },
        {
            Name: "_JAR",
            Provider: "Google",
            Purpose: "Collects information on user behaviour on multiple websites. This information is used in order to optimize the relevance of dvertisements on the website.",
            "Maximum Storage Duration": "30 days",
            Type: "HTTP Cookie"
        },
        {
            Name: "APISID",
            Provider: "Google",
            Purpose: "Pending",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "AWSALB",
            Provider: "api.sirv.com",
            Purpose: "Registers which server-cluster is serving the visitor. This is used in context with load balancing, in order to optimize user xperience.",
            "Maximum Storage Duration": "7 days",
            "Typ": "HTTP Cookie"
        },
        {
            Name: "AWSALBCORS [x2]",
            Provider: "api.sirv.com, cdn.sirv.com",
            Purpose: "Registers which server-cluster is serving the visitor. This is used in context with load balancing, in order to optimize user xperience.",
            "Maximum Storage Duration": "7 days",
            "Typ": "HTTP Cookie"
        },
        {
            Name: "CookieConsent [x2]",
            Provider: "Cookiebot",
            Purpose: "Stores the user's cookie consent state for the current domain",
            "Maximum Storage Duration": "120 days",
            Type: "HTTP Cookie"
        },
        {
            Name: "cookietest",
            Provider: "js.sirv.com",
            Purpose: "This cookie is used to determine if the visitor has accepted the cookies.",
            "Maximum Storage Duration": "Session",
            Type: "HTTP Cookie"
        },
        {
            Name: "datadome",
            Provider: "dd.copy.ai",
            Purpose: "Used in context with the website’s BotManager. The BotManager detects and mitigates bots trying to access the website.",
            "Maximum Storage Duration": "1 year",
            Type: "HTTP Cookie"
        },
        {
            Name: "HSID",
            Provider: "Google",
            Purpose: "Pending",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "_lipt",
            Provider: "LinkedIn",
            Purpose: "Stores the user's cookie consent state for the current domain",
            "Maximum Storage Duration": "180 days",
            Type: "HTTP Cookie"
        },
        {
            Name: "NID",
            Provider: "Google",
            Purpose: "Registers a unique ID that identifies a returning user's device. The ID is used for targeted ads.",
            "Maximum Storage Duration": "180 days",
            Type: "HTTP Cookie"
        },
        {
            Name: "objectId@0.0#.#.#.##@#.##",
            Provider: "embed.sequoi.io",
            Purpose: "Holds the user's timezone.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTTP Cookie"
        },
        {
            Name: "omSessionId",
            Provider: "OptinMonster",
            Purpose: "Saves the user's screen size in order to adjust the size of images on the website.",
            "Maximum Storage Duration": "Session",
            Type: "HTTP Cookie"
        },
        {
            Name: "persist:root",
            Provider: "scribehow.com",
            Purpose: "This cookie stores visitor credentials in an encrypted cookie to allow the visitor to stay logged in between visits, if the isitor has accepted the 'Stay logged in' button.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTTP Cookie"
        },
        {
            Name: "SAPISID",
            Provider: "Google",
            Purpose: "Pending",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "sentry.offlineRequest",
            Provider: "cdn.sentry.io",
            Purpose: "Detects and logs potential errors on third-party provided functions on the website.",
            "Maximum Storage Duration": "Session",
            Type: "IndexedDB"
        },
        {
            Name: "SID",
            Provider: "Google",
            Purpose: "Pending",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "SIDCC",
            Provider: "Google",
            Purpose: "Pending",
            "Maximum Storage Duration": "1 year",
            Type: "HTTP Cookie"
        },
        {
            Name: "SSID",
            Provider: "Google",
            Purpose: "Registers a unique ID that is used by Google to keep statistics of how the visitor uses YouTube videos across different websites.",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "wf_auth_page",
            Provider: "www.copy.ai",
            Purpose: "This cookie is necessary for the login function on the website.",
            "Maximum Storage Duration": "Session",
            Type: "HTTP Cookie"
        }
    ]
},
{
    category: "Preferences (7)",
    description: "Preference cookies enable a website to remember information that changes the way the website behaves or looks, like your preferred language or the region that you are in.",
    columns: [
        "Name",
        "Provider",
        "Purpose",
        "Maximum Storage Duration",
        "Type"
    ],
    "rows": [
        {
            Name: "firebaseLocalStoragedb#firebaseLocalStorage",
            Provider: "Google",
            Purpose: "Facilitates the notification function within the chatbox, allowing the website’s support team to notify the user, when a reply has been given in the chatbox.",
            "Maximum Storage Duration": "Persistent",
            Type: "IndexedDB"
        },
        {
            Name: "intercom.intercom-state [x2]",
            Provider: "app.copy.ai",
            Purpose: "Stores a unique ID string for each chat-box session. This allows the website-support to see previous issues and reconnect with the previous supporter.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTML Local Storage"
        },
        {
            Name: "intercom-device-id-#",
            Provider: "Intercom",
            Purpose: "Sets a specific ID for the user which ensures the integrity of the website’s chat function.",
            "Maximum Storage Duration": "271 days",
            Type: "HTTP Cookie"
        },
        {
            Name: "intercom-id-#",
            Provider: "Intercom",
            Purpose: "Allows the website to recognise the visitor, in order to optimize the chat-box functionality.",
            "Maximum Storage Duration": "271 days",
            Type: "HTTP Cookie"
        },
        {
            Name: "intercom-session-#",
            Provider: "Intercom",
            Purpose: "Sets a specific ID for the user which ensures the integrity of the website’s chat function.",
            "Maximum Storage Duration": "7 days",
            Type: "HTTP Cookie"
        },
        {
            Name: "lidc",
            Provider: "LinkedIn",
            Purpose: "Registers which server-cluster is serving the visitor. This is used in context with load balancing, in order to optimize user experience.",
            "Maximum Storage Duration": "1 day",
            Type: "HTTP Cookie"
        }
    ]
},
{
    category: "Statistics (20)",
    description: "Statistic cookies help website owners to understand how visitors interact with websites by collecting and reporting information anonymously.",
    columns: [
        "Name",
        "Provider",
        "Purpose",
        "Maximum Storage Duration",
        "Type"
    ],
    "rows": [
        {
            Name: "_ga",
            Provider: "Google",
            Purpose: "Registers a unique ID that is used to generate statistical data on how the visitor uses the website.",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "_ga_#",
            Provider: "Google",
            Purpose: "Used by Google Analytics to collect data on the number of times a user has visited the website as well as dates for the first and most recent visit.",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "_gat",
            Provider: "Google",
            Purpose: "Used by Google Analytics to throttle request rate.",
            "Maximum Storage Duration": "1 day",
            Type: "HTTP Cookie"
        },
        {
            Name: "_omappvp",
            Provider: "OptinMonster",
            Purpose: "This cookie is used to determine if the visitor has visited the website before, or if it is a new visitor on the website.",
            "Maximum Storage Duration": "11 years",
            Type: "HTTP Cookie"
        },
        {
            Name: "_omappvs",
            Provider: "OptinMonster",
            Purpose: "This cookie is used to determine if the visitor has visited the website before, or if it is a new visitor on the website.",
            "Maximum Storage Duration": "1 day",
            Type: "HTTP Cookie"
        },
        {
            Name: "_tdtest_f[x2]",
            Provider: "embed.sequel.io",
            Purpose: "Registers statistical data on users' behaviour on the website. Used for internal analytics by the website operator.",
            "Maximum Storage Duration": "Session",
            Type: "HTTP Cookie"
        },
        {
            Name: "ajs_anonymous_id[x2]",
            Provider: "Segment cdn.jsdeliver.net",
            Purpose: "This cookie is used to count how many times a website has been visited by different visitors - this is done by assigning the visitor an ID, so the visitor does not get registered twice.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTML Local Storage"
        },
        {
            Name: "ajs_anonymous_id[x2]",
            Provider: "Segment demo.arcade.software",
            Purpose: "This cookie is used to identify a specific visitor - this information is used to identify the number of specific visitors on a website.",
            "Maximum Storage Duration": "1 year",
            Type: "HTML Local Storage"
        },
        {
            Name: "amp_#",
            Provider: "embed.sequel.io",
            Purpose: "Registers statistical data on users' behaviour on the website. Used for internal analytics by the website operator.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTML Local Storage"
        },
        {
            Name: "amplitude_unsent_#",
            Provider: "embed.sequel.io",
            Purpose: "Registers data on visitors' website-behaviour. This is used for internal analysis and website optimization.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTML Local Storage"
          },
          {
            Name: "amplitude_unsent_identify_#",
            Provider: "embed.sequel.io",
            Purpose: "Registers data on visitors' website-behaviour. This is used for internal analysis and website optimization.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTML Local Storage"
          },
          {
            Name: "collect",
            Provider: "Google",
            Purpose: "Used to send data to Google Analytics about the visitor's device and behavior. Tracks the visitor across devices and marketing channels.",
            "Maximum Storage Duration": "Session",
            Type: "Pixel Tracker"
          },
          {
            Name: "omLastSeen",
            Provider: "OptinMonster",
            Purpose: "This cookie is used to determine if the visitor has visited the website before, or if it is a new visitor on the website.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTML Local Storage"
          },
          {
            Name: "omSessionPageviews",
            Provider: "OptinMonster",
            Purpose: "This cookie is used to identify the frequency of visits and how long the visitor is on the website. The cookie is also used to determine how many and which subpages the visitor visits on a website – this information can be used by the website to optimize the domain and its subpages.",
            "Maximum Storage Duration": "Session",
            Type: "HTML Local Storage"
          },
          {
            Name: "omSessionStart",
            Provider: "OptinMonster",
            Purpose: "Sets a timestamp for when the visitor entered the website. This is used for analytical purposes on the website.",
            "Maximum Storage Duration": "Session",
            Type: "HTML Local Storage"
          },
          {
            Name: "omVisitsFirst",
            Provider: "OptinMonster",
            Purpose: "This cookie is used to count how many times a website has been visited by different visitors - this is done by assigning the visitor an ID, so the visitor does not get registered twice.",
            "Maximum Storage Duration": "Persistent",
            Type: "HTML Local Storage"
          },
          {
            Name: "vuid",
            Provider: "Vimeo",
            Purpose: "Collects data on the user's visits to the website, such as which pages have been read.",
            "Maximum Storage Duration": "2 years",
            Type: "HTTP Cookie"
          }
    ]
},
{
    category: "Marketing (40)",
    description: "Marketing cookies are used to track visitors across websites. The intention is to display ads that are relevant and engaging for the individual user and thereby more valuable for publishers and third party advertisers.",
    columns: [
      "Name",
      "Provider",
      "Purpose",
      "Maximum Storage Duration",
      "Type"
    ],
    "rows": [
      {
        Name: "#-#",
        Provider: "YouTube",
        Purpose: "Used to track user's interaction with embedded content.",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      },
      {
        Name: "_mpq_f_#",
        Provider: "scribehow.com",
        Purpose: "Collects data on user behaviour and interaction in order to optimize the website and make advertisement on the website more relevant.",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "_td[_x3]",
        Provider: "demo.arcade.software, Segment",
        Purpose: "Used to track visitors on multiple websites, in order to present relevant advertisement based on the visitor's preferences.",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "_gcl_au",
        Provider: "Google",
        Purpose: "Used by Google AdSense for experimenting with advertisement efficiency across websites using their services.",
        "Maximum Storage Duration": "3 months",
        Type: "HTTP Cookie"
      },
      {
        Name: "-6248cbc39a7c7",
        Provider: "Pending",
        Purpose: "N/A",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      },
      {
        Name: "ajs_user_id [x2]",
        Provider: "Segment cdn.jsdeliver.net",
        Purpose: "Collects data on visitors' preferences and behaviour on the website - This information is used make content and advertisement more relevant to the specific visitor.",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "ajs_user_id [x2]",
        Provider: "demo.arcade.software",
        Purpose: "This cookie is used to collect data on the visitor's behavior on the website - this information can be used to assign the visitor to a visitor segment, based on common preferences.",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "bcookie",
        Provider: "LinkedIn",
        Purpose: "Used by the social networking service, LinkedIn, for tracking the use of embedded services.",
        "Maximum Storage Duration": "1 year",
        Type: "HTTP Cookie"
      },
      {
        Name: "IDE",
        Provider: "Google",
        Purpose: "Used by Google DoubleClick to register and report the website user's actions after viewing or clicking one of the advertiser's ads with the purpose of measuring the efficacy of an ad and to present targeted ads to the user.",
        "Maximum Storage Duration": "400 days",
        Type: "HTTP Cookie"
      },
      {
        Name: "iJ5q-lO9@$",
        Provider: "YouTube",
        Purpose: "Registers a unique ID to keep statistics of what videos from YouTube the user has seen.",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      },
      {
        Name: "LAST_RESULT_ENTRY_KEY",
        Provider: "YouTube",
        Purpose: "Used to track user's interaction with embedded content.",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "LogsDatabaseV2V#|LogsRequestsStore",
        Provider: "YouTube",
        Purpose: "Used to track user's interaction with embedded content.",
        "Maximum Storage Duration": "Persistent",
        Type: "IndexedDB"
      },
      {
        Name: "mp_#_mixpanel",
        Provider: "scribehow.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "1 year",
        Type: "HTTP Cookie"
      },
      {
        Name: "nextId",
        Provider: "YouTube",
        Purpose: "Used to track user's interaction with embedded content.",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "omFoldersSeen",
        Provider: "OptinMonster",
        Purpose: "Used in context with the website's pop-up questionnaires and messengering. The data is used for statistical or marketing purposes.",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "pagead/1p-conversion/#",
        Provider: "Google",
        Purpose: "Pending",
        "Maximum Storage Duration": "Session",
        Type: "Pixel Tracker"
      },
      {
        Name: "pagead/1p-user-list/#",
        Provider: "Google",
        Purpose: "Tracks if the user has shown interest in specific products or events across multiple websites and detects how the user navigates between sites. This is used for measurement of advertisement efforts and facilitates payment of referral-fees between websites.",
        "Maximum Storage Duration": "Session",
        Type: "Pixel Tracker"
      },
      {
        Name: "pagead/landing",
        Provider: "Google",
        Purpose: "Collects data on visitor behaviour from multiple websites, in order to present more relevant advertisement - This also allows the website to limit the number of times that they are shown the same advertisement.",
        "Maximum Storage Duration": "Session",
        Type: "Pixel Tracker"
      },
      {
        Name: "pardot",
        Provider: "go.copy.ai",
        Purpose: "Used in content with Account-Based-Marketing (ABM). The cookie registers data such as IP addresses, time spent on the website and page requests for the visit. This is used for retargeting of multiple users coming from the same IP addresses. ABM usually facilitates B2B marketing purposes.",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "remote_sid",
        Provider: "YouTube",
        Purpose: "Necessary for the implementation and functionality of YouTube video-content on the website.",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "requests",
        Provider: "YouTube",
        Purpose: "Used to track user's interaction with embedded content.",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "ServiceWorkerLogsDatabaseV5WHealthLog",
        Provider: "YouTube",
        Purpose: "Necessary for the implementation and functionality of YouTube video-content on the website.",
        "Maximum Storage Duration": "Persistent",
        Type: "IndexedDB"
      },
      {
        Name: "test_cookie",
        Provider: "Google",
        Purpose: "Used to check if the user's browser supports cookies.",
        "Maximum Storage Duration": "1 day",
        Type: "HTTP Cookie"
      },
      {
        Name: "TESTCOOKIESSENAB",
        Provider: "YouTube",
        Purpose: "Used to track user's interaction with embedded content.",
        "Maximum Storage Duration": "1 day",
        Type: "HTTP Cookie"
      },
      {
        Name: "VISITOR_INFO1_LIVE",
        Provider: "YouTube",
        Purpose: "Tries to estimate the users' bandwidth on pages with integrated YouTube videos.",
        "Maximum Storage Duration": "180 days",
        Type: "HTTP Cookie"
      },
      {
        Name: "YSC",
        Provider: "YouTube",
        Purpose: "Registers a unique ID to keep statistics of what videos from YouTube the user has seen.",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "yt-remote-device-id",
        Provider: "YouTube",
        Purpose: "Registers a unique ID to keep statistics of what videos from YouTube the user has seen.",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "yt-player-bandwidth",
        Provider: "YouTube",
        Purpose: "Stores the user's video player preferences using embedded YouTube video.",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "YtdbMetadatabase",
        Provider: "YouTube",
        Purpose: "Used to track user's interaction with embedded content.",
        "Maximum Storage Duration": "Persistent",
        Type: "IndexedDB"
      },
      {
        Name: "yt-remote-cast-available",
        Provider: "YouTube",
        Purpose: "Stores the user's video player preferences using embedded YouTube video.",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      },
      {
        Name: "yt-remote-cast-installed",
        Provider: "YouTube",
        Purpose: "Stores the user's video player preferences using embedded YouTube video.",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      },
      {
        Name: "yt-remote-connected-devices",
        Provider: "YouTube",
        Purpose: "Stores the user's video player preferences using embedded YouTube video",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "yt-remote-device-id",
        Provider: "YouTube",
        Purpose: "Stores the user's video player preferences using embedded YouTube video",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "yt-remote-fast-check-period",
        Provider: "YouTube",
        Purpose: "Stores the user's video player preferences using embedded YouTube video",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      },
      {
        Name: "yt-remote-session-app",
        Provider: "YouTube",
        Purpose: "Stores the user's video player preferences using embedded YouTube video",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      },
      {
        Name: "yt-remote-session-name",
        Provider: "YouTube",
        Purpose: "Stores the user's video player preferences using embedded YouTube video",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      }
    ]
  },
  {
    category: "Unclassified (16)",
    description: "Unclassified cookies are cookies that we are in the process of classifying, together with the providers of individual cookies.",
    columns: [
        "Name",
        "Provider",
        "Purpose",
        "Maximum Storage Duration",
        "Type"
    ],
    "rows": [
      {
        Name: "AWSALBCORS",
        Provider: "cdn-apac01.me",
        Purpose: "Pending",
        "Maximum Storage Duration": "7 days",
        Type: "HTTP Cookie"
      },
      {
        Name: "AWSALB",
        Provider: "cdn-apac01.me",
        Purpose: "Pending",
        "Maximum Storage Duration": "7 days",
        Type: "HTTP Cookie"
      },
      {
        Name: "ajs_anonymous_id",
        Provider: "app.copy.ai",
        Purpose: "Pending",
        "Maximum Storage Duration": "1 year",
        Type: "HTML Local Storage"
      },
      {
        Name: "ajs_user_id",
        Provider: "app.copy.ai",
        Purpose: "Pending",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "amplitude_id_*",
        Provider: "app.copy.ai",
        Purpose: "Pending",
        "Maximum Storage Duration": "Session",
        Type: "HTML Local Storage"
      },
      {
        Name: "AWSALB",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "7 days",
        Type: "HTTP Cookie"
      },
      {
        Name: "AWSALBCORS",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "7 days",
        Type: "HTTP Cookie"
      },
      {
        Name: "http_referrer",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "pf_pf_*",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "10 years",
        Type: "HTTP Cookie"
      },
      {
        Name: "pf_pf_*",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "24 days",
        Type: "HTTP Cookie"
      },
      {
        Name: "pf_pf_*",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "2 months",
        Type: "HTTP Cookie"
      },
      {
        Name: "pf_pf_*",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "1 month",
        Type: "HTTP Cookie"
      },
      {
        Name: "pf_pf_*",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "pf_pf_*",
        Provider: "app.copy.ai",
        Purpose: "Pending",
        "Maximum Storage Duration": "Session",
        Type: "HTTP Cookie"
      },
      {
        Name: "user_uuid",
        Provider: "api.pathfactory.com",
        Purpose: "Pending",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      },
      {
        Name: "vt_data",
        Provider: "app.copy.ai",
        Purpose: "Pending",
        "Maximum Storage Duration": "Persistent",
        Type: "HTML Local Storage"
      }
    ]
  }

]